/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}/workbench": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncidentWorkbench"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}/reinvestigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reinvestigateIncident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}/actions/{action_id}/approve-and-execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveAndExecute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvestigationEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamInvestigationEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}/human-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitHumanInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{id}/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["controlInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminState"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/admin/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeams"];
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/api/v1/admin/team-memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeamMemberships"];
        put?: never;
        post: operations["createTeamMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/team-memberships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTeamMembership"];
        trace?: never;
    };
    "/api/v1/admin/role-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoleBindings"];
        put?: never;
        post: operations["createRoleBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/role-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateRoleBinding"];
        trace?: never;
    };
    "/api/v1/admin/approval-authorities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApprovalAuthorities"];
        put?: never;
        post: operations["createApprovalAuthority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/approval-authorities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateApprovalAuthority"];
        trace?: never;
    };
    "/api/v1/admin/connector-enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConnectorAdminState"];
        put?: never;
        post: operations["createConnectorEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connector-enrollments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateConnectorEnrollment"];
        trace?: never;
    };
    "/api/v1/admin/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRegisteredClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateRegisteredCluster"];
        trace?: never;
    };
    "/api/v1/admin/connector-commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["queueConnectorReadCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/resource-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getResourceCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCatalogServices"];
        put?: never;
        post: operations["createCatalogService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/resource-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listResourceBindings"];
        put?: never;
        post: operations["confirmResourceBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/resource-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["correctResourceBinding"];
        trace?: never;
    };
    "/api/v1/connectors/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordConnectorHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/commands/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pollConnectorCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/commands/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startConnectorCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/commands/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitConnectorCommandResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/discovery-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshDiscoveryCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
            /** @constant */
            session_mode: "cookie";
        };
        LoginResponse: {
            service?: string;
            /** @constant */
            status: "ok";
            request_id: string;
            expires_at: number;
            actor: components["schemas"]["Actor"];
        };
        LegacyActor: {
            actor_id: string;
            username: string;
            display_name: string;
            roles: string[];
            permissions: string[];
        };
        Actor: {
            id: string;
            username: string;
            display_name: string;
            roles: ("platform_administrator" | "sre")[];
            capabilities: string[];
            is_platform_administrator: boolean;
        };
        Incident: {
            id: string;
            title: string;
            /** @enum {unknown} */
            severity: "critical" | "high" | "medium" | "low";
            /** @enum {unknown} */
            status: "active" | "resolved";
            /** @enum {unknown} */
            lifecycle_state: "firing" | "stabilizing" | "resolved" | "reopened";
            /** @enum {unknown} */
            binding_status: "bound" | "unbound";
            cluster_id: string;
            cluster_name: string;
            /** @enum {unknown} */
            environment: "prod" | "staging" | "dev" | "test";
            namespace: string;
            alertname: string;
            workload_name: string | null;
            service_name: string | null;
            team_name: string | null;
            signal_count: number;
            evidence_revision: number;
            resolved_at: number | null;
            reopened_at: number | null;
            created_at: number;
            updated_at: number;
        };
        AlertSignal: {
            fingerprint: string;
            alertname: string;
            /** @enum {unknown} */
            status: "firing" | "recovered";
            /** @enum {unknown} */
            severity: "critical" | "high" | "medium" | "low";
            summary: string;
            workload_kind: string | null;
            workload_name: string | null;
            started_at: string | null;
            created_at: number;
            updated_at: number;
        };
        InvestigationSummary: {
            id: string;
            sequence: number;
            /** @enum {unknown} */
            status: "queued" | "running" | "paused" | "human_led" | "completed" | "failed" | "terminated";
            created_at: number;
            updated_at: number;
        };
        EvidenceScope: {
            cluster_id: string;
            namespace: string;
            workload_kind: string | null;
            workload_name: string | null;
        };
        EvidenceStep: {
            id: string;
            sequence: number;
            purpose: string;
            source: string;
            scope: components["schemas"]["EvidenceScope"];
            /** @enum {unknown} */
            state: "running" | "succeeded" | "partial" | "failed" | "skipped";
            result: string | null;
            impact: string;
            evidence_references: string[];
            missing_guidance: string | null;
            observed_at: number;
            expires_at: number;
        };
        InvestigationJudgment: {
            summary: string;
            valid: boolean;
            /** @enum {unknown} */
            evidence_gate_status: "complete" | "incomplete";
            next_evidence_guidance: string[];
        };
        RecommendedActionTarget: {
            cluster_id: string;
            namespace: string;
            workload_kind: string | null;
            workload_name: string | null;
            deployment_target_id: string | null;
            resource_binding_id: string | null;
            binding_revision: number | null;
        };
        EvidenceGateResult: {
            /** @enum {unknown} */
            status: "complete" | "incomplete";
            approvable: boolean;
            reasons: string[];
        };
        RecommendedAction: {
            id: string;
            version: number;
            action_type: string;
            summary: string;
            target: components["schemas"]["RecommendedActionTarget"];
            parameters: {
                [key: string]: unknown;
            };
            evidence_step_ids: string[];
            safeguards: string[];
            rollback_plan: {
                [key: string]: unknown;
            } | null;
            gate: components["schemas"]["EvidenceGateResult"];
            hash: string;
            stale: boolean;
            expires_at: number;
            can_approve: boolean;
            approval_id: string | null;
            execution: components["schemas"]["MutationExecution"] | null;
        };
        MutationExecution: {
            command_id: string;
            /** @enum {unknown} */
            status: "queued" | "leased" | "started" | "succeeded" | "failed" | "rejected" | "unknown_outcome";
            result: components["schemas"]["ConnectorCommandTerminalResult"] | null;
        };
        IncidentResourceContext: {
            cluster_id: string;
            cluster_name: string;
            /** @enum {unknown} */
            environment: "prod" | "staging" | "dev" | "test";
            /** @enum {unknown} */
            runtime_status: "online" | "offline" | "degraded";
            namespace: string;
            workload_kind: string | null;
            workload_name: string | null;
            deployment_target_id: string | null;
            service_id: string | null;
            service_name: string | null;
            team_id: string | null;
            resource_binding_id: string | null;
            binding_revision: number | null;
        };
        IncidentResponsibility: {
            /** @enum {unknown} */
            status: "assigned" | "unassigned";
            team_id: string | null;
            team_name: string | null;
        };
        RecoveryObservation: {
            id: string;
            evidence_revision: number;
            /** @enum {unknown} */
            status: "stabilizing" | "cancelled" | "resolved";
            observed_at: number;
            stabilizes_at: number;
            cancelled_at: number | null;
            resolved_at: number | null;
        };
        ActorResponse: {
            request_id: string;
            actor: components["schemas"]["Actor"];
        };
        IncidentListResponse: {
            request_id: string;
            incidents: components["schemas"]["Incident"][];
        };
        WorkbenchResponse: {
            request_id: string;
            incident: components["schemas"]["Incident"];
            resource_context: components["schemas"]["IncidentResourceContext"];
            alert_signals: components["schemas"]["AlertSignal"][];
            investigation: components["schemas"]["InvestigationSummary"] | null;
            evidence_steps: components["schemas"]["EvidenceStep"][];
            judgment: components["schemas"]["InvestigationJudgment"] | null;
            recommended_actions: components["schemas"]["RecommendedAction"][];
            recovery_observation: components["schemas"]["RecoveryObservation"] | null;
            responsibility: components["schemas"]["IncidentResponsibility"];
            actor_capabilities: string[];
            snapshot_revision: string;
            event_cursor: number;
        };
        InvestigationEvent: {
            id: number;
            investigation_id: string;
            type: string;
            actor_id: string | null;
            payload: {
                [key: string]: unknown;
            };
            created_at: number;
        };
        InvestigationEventsResponse: {
            request_id: string;
            events: components["schemas"]["InvestigationEvent"][];
            next_cursor: number;
            has_more: boolean;
        };
        InvestigationEventResponse: {
            request_id: string;
            event: components["schemas"]["InvestigationEvent"];
        };
        HumanInputRequest: {
            /** @enum {unknown} */
            kind: "assertion" | "correction" | "retraction";
            content: string;
            target_event_id?: number;
            idempotency_key: string;
        };
        InvestigationControlRequest: {
            /** @enum {unknown} */
            action: "pause" | "takeover" | "terminate";
            idempotency_key: string;
        };
        ReinvestigateRequest: {
            idempotency_key: string;
        };
        InvestigationResponse: {
            request_id: string;
            investigation: components["schemas"]["InvestigationSummary"];
        };
        AdminUser: {
            id: string;
            username: string;
            display_name: string;
            email?: string | null;
            active: boolean;
            updated_at: number;
        };
        UserCreateRequest: {
            username: string;
            display_name: string;
            email?: string | null;
            password: string;
            reason: string;
        };
        UserUpdateRequest: {
            display_name?: string;
            email?: string | null;
            password?: string;
            active?: boolean;
            reason: string;
        };
        TeamCreateRequest: {
            name: string;
            description?: string;
            reason: string;
        };
        TeamUpdateRequest: {
            name?: string;
            description?: string;
            active?: boolean;
            reason: string;
        };
        TeamMembershipCreateRequest: {
            user_id: string;
            team_id: string;
            reason: string;
        };
        TeamMembershipUpdateRequest: {
            active: boolean;
            reason: string;
        };
        RoleBindingCreateRequest: components["schemas"]["PlatformAdminBindingCreateRequest"] | components["schemas"]["SreBindingCreateRequest"];
        PlatformAdminBindingCreateRequest: {
            user_id: string;
            /** @constant */
            role: "platform_administrator";
            /** @constant */
            scope_type: "platform";
            scope_id?: null;
            reason: string;
        };
        SreBindingCreateRequest: {
            user_id: string;
            /** @constant */
            role: "sre";
            /** @constant */
            scope_type: "team";
            scope_id: string;
            reason: string;
        };
        RoleBindingUpdateRequest: {
            active: boolean;
            reason: string;
        };
        AdminTeam: {
            id: string;
            name: string;
            description: string;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        AdminTeamMembership: {
            id: string;
            user_id: string;
            team_id: string;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        AdminRoleBinding: {
            id: string;
            user_id: string;
            /** @enum {unknown} */
            role: "platform_administrator" | "sre";
            /** @enum {unknown} */
            scope_type: "platform" | "team";
            scope_id?: string | null;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        ApprovalAuthority: {
            id: string;
            user_id: string;
            /** @enum {unknown} */
            environment: "*" | "prod" | "staging" | "dev" | "test";
            /** @enum {unknown} */
            scope_type: "platform" | "team" | "service" | "deployment_target";
            scope_id: string | null;
            active: boolean;
        };
        ApprovalAuthorityCreateRequest: {
            user_id: string;
            /** @enum {unknown} */
            environment: "*" | "prod" | "staging" | "dev" | "test";
            /** @enum {unknown} */
            scope_type: "platform" | "team" | "service" | "deployment_target";
            scope_id: string | null;
            reason: string;
        };
        ApprovalAuthorityUpdateRequest: {
            active: boolean;
            reason: string;
        };
        ApprovalAuthorityListResponse: {
            request_id: string;
            approval_authorities: components["schemas"]["ApprovalAuthority"][];
        };
        ApprovalAuthorityResponse: {
            request_id: string;
            approval_authority: components["schemas"]["ApprovalAuthority"];
        };
        ApproveAndExecuteRequest: {
            action_version: number;
            action_hash: string;
            idempotency_key: string;
        };
        GovernedExecution: {
            approval_id: string;
            action_id: string;
            action_version: number;
            execution_grant_id: string;
            expires_at: number;
            command_id: string;
            idempotent: boolean;
        };
        ApproveAndExecuteResponse: {
            request_id: string;
            execution: components["schemas"]["GovernedExecution"];
        };
        ConnectorEnrollment: {
            id: string;
            connector_id: string;
            cluster_id: string;
            active: boolean;
            registered: boolean;
        };
        Cluster: {
            cluster_id: string;
            connector_id: string;
            display_name: string;
            /** @enum {unknown} */
            environment: "prod" | "staging" | "dev" | "test";
            governance_notes: string;
            mutation_enabled: boolean;
            /** @enum {unknown} */
            runtime_status: "online" | "offline" | "degraded";
            failure_summary: string;
            last_heartbeat: number;
            pending_read_commands?: number;
            last_read_command?: components["schemas"]["ConnectorCommandSummary"] | null;
            last_read_result?: components["schemas"]["ConnectorCommandResultSummary"] | null;
        };
        ConnectorEnrollmentCreateRequest: {
            connector_id: string;
            cluster_id: string;
            reason: string;
        };
        ConnectorEnrollmentUpdateRequest: {
            active?: boolean;
            rotate_credential?: boolean;
            reason: string;
        };
        ClusterUpdateRequest: {
            display_name?: string;
            /** @enum {unknown} */
            environment?: "prod" | "staging" | "dev" | "test";
            governance_notes?: string;
            mutation_enabled?: boolean;
            reason: string;
        };
        ConnectorRegistrationRequest: {
            connector_id: string;
            cluster_id: string;
            namespace_scope?: string[];
            capabilities?: string[];
        };
        ConnectorHeartbeatRequest: {
            connector_id: string;
            cluster_id: string;
            /** @enum {unknown} */
            status: "online" | "degraded";
            failure_summary?: string;
        };
        ConnectorReadParameters: {
            /** @enum {unknown} */
            resource_kind: "pods" | "deployments" | "services" | "events";
            name?: string;
            selector?: string;
            /**
             * @default json
             * @enum {unknown}
             */
            output: "json" | "yaml" | "wide";
        };
        ConnectorCommandCreateRequest: {
            cluster_id: string;
            namespace: string;
            /** @constant */
            action: "get_resource";
            parameters: components["schemas"]["ConnectorReadParameters"];
            reason: string;
        };
        ConnectorCommandPollRequest: {
            connector_id: string;
            cluster_id: string;
            wait_seconds: number;
        };
        ConnectorCommandStartRequest: {
            connector_id: string;
            cluster_id: string;
            lease_id: string;
        };
        ConnectorCommandTerminalResult: {
            /** @enum {unknown} */
            status: "succeeded" | "failed" | "rejected";
            stdout: string;
            stderr: string;
            exit_code: number | null;
            truncated: boolean;
            error_code: string | null;
            error_message: string | null;
        };
        ConnectorCommandResultSubmitRequest: {
            connector_id: string;
            cluster_id: string;
            lease_id: string;
            result: components["schemas"]["ConnectorCommandTerminalResult"];
        };
        ConnectorCommand: {
            id: string;
            cluster_id: string;
            namespace: string;
            /** @enum {unknown} */
            action: "get_resource" | "restart_deployment" | "scale_deployment" | "rollback_deployment";
            parameters: {
                [key: string]: unknown;
            };
            rollback_plan: {
                [key: string]: unknown;
            } | null;
            execution_grant_id: string | null;
            execution_grant_expires_at: number | null;
            action_hash: string | null;
            /** @enum {unknown} */
            status: "queued" | "leased" | "started" | "succeeded" | "failed" | "rejected" | "unknown_outcome";
            attempt_count: number;
            lease_id: string | null;
            lease_expires_at: number | null;
            created_at: number;
            result: components["schemas"]["ConnectorCommandTerminalResult"] | null;
        };
        ConnectorCommandSummary: {
            id: string;
            namespace: string;
            /** @constant */
            action: "get_resource";
            /** @enum {unknown} */
            status: "queued" | "leased" | "started" | "succeeded" | "failed" | "rejected";
            attempt_count: number;
            created_at: number;
        };
        ConnectorCommandResultSummary: {
            id: string;
            namespace: string;
            /** @constant */
            action: "get_resource";
            /** @enum {unknown} */
            status: "succeeded" | "failed" | "rejected";
            attempt_count: number;
            created_at: number;
            result_received_at: number;
            error_code: string | null;
        };
        ConnectorCommandResponse: {
            request_id: string;
            command: components["schemas"]["ConnectorCommand"];
        };
        ConnectorCommandPollResponse: {
            request_id: string;
            command: components["schemas"]["ConnectorCommand"] | null;
        };
        ConnectorCommandStartResponse: {
            request_id: string;
            id: string;
            /** @constant */
            status: "started";
            /** @constant */
            acknowledged: true;
        };
        ConnectorCommandResultResponse: {
            request_id: string;
            id: string;
            /** @enum {unknown} */
            status: "succeeded" | "failed" | "rejected";
            idempotent: boolean;
            late: boolean;
        };
        DiscoveryObservation: {
            namespace: string;
            workload_kind: string;
            workload_name: string;
            service_name?: string | null;
            service_hint?: string | null;
            team_hint?: string | null;
        };
        DiscoveryRefreshRequest: {
            connector_id: string;
            cluster_id: string;
            candidates: components["schemas"]["DiscoveryObservation"][];
        };
        DiscoveryCandidate: {
            id: string;
            cluster_id: string;
            namespace: string;
            workload_kind: string;
            workload_name: string;
            service_name: string | null;
            service_hint: string | null;
            team_hint: string | null;
            first_seen_at: number;
            last_seen_at: number;
            deployment_target_id: string | null;
            resource_binding_id: string | null;
            /** @enum {unknown} */
            binding_status: "bound" | "unbound";
        };
        CatalogService: {
            id: string;
            team_id: string;
            name: string;
            description: string;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        DeploymentTarget: {
            id: string;
            candidate_id: string;
            cluster_id: string;
            namespace: string;
            workload_kind: string;
            workload_name: string;
            service_identity: string | null;
            created_at: number;
        };
        ResourceBinding: {
            id: string;
            deployment_target_id: string;
            service_id: string;
            team_id: string;
            revision: number;
            confirmed_by: string;
            confirmed_at: number;
            updated_at: number;
        };
        ServiceCreateRequest: {
            team_id: string;
            name: string;
            description?: string;
            reason: string;
        };
        ResourceBindingCreateRequest: {
            candidate_id: string;
            service_id: string;
            reason: string;
        };
        ResourceBindingUpdateRequest: {
            service_id: string;
            reason: string;
        };
        DiscoveryRefreshResponse: {
            request_id: string;
            discovery_candidates: components["schemas"]["DiscoveryCandidate"][];
        };
        ResourceCatalogStateResponse: {
            request_id: string;
            discovery_candidates: components["schemas"]["DiscoveryCandidate"][];
            services: components["schemas"]["CatalogService"][];
            deployment_targets: components["schemas"]["DeploymentTarget"][];
            resource_bindings: components["schemas"]["ResourceBinding"][];
        };
        ServiceResponse: {
            request_id: string;
            service: components["schemas"]["CatalogService"];
        };
        ResourceBindingResponse: {
            request_id: string;
            resource_binding: components["schemas"]["ResourceBinding"];
        };
        ConnectorAdminStateResponse: {
            request_id: string;
            connector_enrollments: components["schemas"]["ConnectorEnrollment"][];
            clusters: components["schemas"]["Cluster"][];
        };
        ConnectorEnrollmentCredentialResponse: {
            request_id: string;
            connector_enrollment: components["schemas"]["ConnectorEnrollment"];
            credential?: string;
        };
        ClusterResponse: {
            request_id: string;
            cluster: components["schemas"]["Cluster"];
        };
        ConnectorClusterResponse: {
            request_id: string;
            /** @enum {unknown} */
            status: "registered" | "accepted";
            cluster: components["schemas"]["Cluster"];
        };
        AdminStateResponse: {
            request_id: string;
            users: components["schemas"]["AdminUser"][];
            teams: components["schemas"]["AdminTeam"][];
            team_memberships: components["schemas"]["AdminTeamMembership"][];
            role_bindings: components["schemas"]["AdminRoleBinding"][];
        };
        AdminUserResponse: {
            request_id: string;
            user: components["schemas"]["AdminUser"];
        };
        AdminTeamResponse: {
            request_id: string;
            team: components["schemas"]["AdminTeam"];
        };
        AdminTeamMembershipResponse: {
            request_id: string;
            team_membership: components["schemas"]["AdminTeamMembership"];
        };
        AdminRoleBindingResponse: {
            request_id: string;
            role_binding: components["schemas"]["AdminRoleBinding"];
        };
        AdminAuditResponse: {
            request_id: string;
            audit: {
                [key: string]: unknown;
            }[];
        };
        CsrfResponse: {
            /** @constant */
            status: "ok";
            request_id: string;
            csrf_token: string;
        };
        OkResponse: {
            /** @constant */
            status: "ok";
            request_id: string;
        };
        ErrorResponse: {
            /** @constant */
            status: "failed";
            request_id: string;
            error: {
                code: string;
                message: string;
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Normalized error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: {
        UserCreate: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        UserUpdate: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        TeamCreate: {
            content: {
                "application/json": components["schemas"]["TeamCreateRequest"];
            };
        };
        TeamUpdate: {
            content: {
                "application/json": components["schemas"]["TeamUpdateRequest"];
            };
        };
        TeamMembershipCreate: {
            content: {
                "application/json": components["schemas"]["TeamMembershipCreateRequest"];
            };
        };
        TeamMembershipUpdate: {
            content: {
                "application/json": components["schemas"]["TeamMembershipUpdateRequest"];
            };
        };
        RoleBindingCreate: {
            content: {
                "application/json": components["schemas"]["RoleBindingCreateRequest"];
            };
        };
        RoleBindingUpdate: {
            content: {
                "application/json": components["schemas"]["RoleBindingUpdateRequest"];
            };
        };
        ConnectorEnrollmentCreate: {
            content: {
                "application/json": components["schemas"]["ConnectorEnrollmentCreateRequest"];
            };
        };
        ConnectorEnrollmentUpdate: {
            content: {
                "application/json": components["schemas"]["ConnectorEnrollmentUpdateRequest"];
            };
        };
        ClusterUpdate: {
            content: {
                "application/json": components["schemas"]["ClusterUpdateRequest"];
            };
        };
        ConnectorCommandCreate: {
            content: {
                "application/json": components["schemas"]["ConnectorCommandCreateRequest"];
            };
        };
        ConnectorCommandPoll: {
            content: {
                "application/json": components["schemas"]["ConnectorCommandPollRequest"];
            };
        };
        ConnectorCommandStart: {
            content: {
                "application/json": components["schemas"]["ConnectorCommandStartRequest"];
            };
        };
        ConnectorCommandResultSubmit: {
            content: {
                "application/json": components["schemas"]["ConnectorCommandResultSubmitRequest"];
            };
        };
        ConnectorRegistration: {
            content: {
                "application/json": components["schemas"]["ConnectorRegistrationRequest"];
            };
        };
        ConnectorHeartbeat: {
            content: {
                "application/json": components["schemas"]["ConnectorHeartbeatRequest"];
            };
        };
        DiscoveryRefresh: {
            content: {
                "application/json": components["schemas"]["DiscoveryRefreshRequest"];
            };
        };
        ServiceCreate: {
            content: {
                "application/json": components["schemas"]["ServiceCreateRequest"];
            };
        };
        ResourceBindingCreate: {
            content: {
                "application/json": components["schemas"]["ResourceBindingCreateRequest"];
            };
        };
        ResourceBindingUpdate: {
            content: {
                "application/json": components["schemas"]["ResourceBindingUpdateRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Cookie session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    reauthenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Fresh authentication recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getActor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listIncidents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible incidents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getIncidentWorkbench: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incident-scoped Workbench snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbenchResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    reinvestigateIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReinvestigateRequest"];
            };
        };
        responses: {
            /** @description Next Investigation created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    approveAndExecute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                action_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveAndExecuteRequest"];
            };
        };
        responses: {
            /** @description Idempotent Approval replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveAndExecuteResponse"];
                };
            };
            /** @description Approval, Execution Grant, and Connector Command created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveAndExecuteResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listInvestigationEvents: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered Investigation Event page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationEventsResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    streamInvestigationEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumable Investigation Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    submitHumanInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumanInputRequest"];
            };
        };
        responses: {
            /** @description Human Input appended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationEventResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    controlInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationControlRequest"];
            };
        };
        responses: {
            /** @description Investigation lifecycle changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationEventResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getAdminState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UserCreate"];
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UserUpdate"];
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamCreate"];
        responses: {
            /** @description Team created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamUpdate"];
        responses: {
            /** @description Team updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listTeamMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createTeamMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamMembershipCreate"];
        responses: {
            /** @description Membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamMembershipResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateTeamMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamMembershipUpdate"];
        responses: {
            /** @description Membership updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamMembershipResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listRoleBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoleBindingCreate"];
        responses: {
            /** @description Role binding created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoleBindingResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoleBindingUpdate"];
        responses: {
            /** @description Role binding updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoleBindingResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listApprovalAuthorities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval Authorities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalAuthorityListResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createApprovalAuthority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalAuthorityCreateRequest"];
            };
        };
        responses: {
            /** @description Approval Authority created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalAuthorityResponse"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateApprovalAuthority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalAuthorityUpdateRequest"];
            };
        };
        responses: {
            /** @description Approval Authority updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalAuthorityResponse"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getConnectorAdminState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector Enrollment and registered Cluster state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorAdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createConnectorEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorEnrollmentCreate"];
        responses: {
            /** @description Enrollment created and credential returned once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorEnrollmentCredentialResponse"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateConnectorEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorEnrollmentUpdate"];
        responses: {
            /** @description Enrollment rotated or revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorEnrollmentCredentialResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listRegisteredClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered Clusters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorAdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateRegisteredCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClusterUpdate"];
        responses: {
            /** @description Cluster governance fields updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterResponse"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    queueConnectorReadCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorCommandCreate"];
        responses: {
            /** @description Durable read command queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorCommandResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getResourceCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource Catalog state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCatalogStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listCatalogServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource Catalog state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCatalogStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createCatalogService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ServiceCreate"];
        responses: {
            /** @description Service created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listResourceBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource Catalog state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCatalogStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    confirmResourceBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ResourceBindingCreate"];
        responses: {
            /** @description Resource Binding confirmed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceBindingResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    correctResourceBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ResourceBindingUpdate"];
        responses: {
            /** @description Resource Binding corrected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceBindingResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    registerConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorRegistration"];
        responses: {
            /** @description Existing authenticated registration refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorClusterResponse"];
                };
            };
            /** @description First authenticated registration created Cluster presence */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorClusterResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    recordConnectorHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorHeartbeat"];
        responses: {
            /** @description Heartbeat recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorClusterResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    pollConnectorCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorCommandPoll"];
        responses: {
            /** @description Atomically leased command or null after long-poll timeout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorCommandPollResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    startConnectorCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorCommandStart"];
        responses: {
            /** @description Command start acknowledged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorCommandStartResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    submitConnectorCommandResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorCommandResultSubmit"];
        responses: {
            /** @description Terminal result accepted or idempotently matched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorCommandResultResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    refreshDiscoveryCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DiscoveryRefresh"];
        responses: {
            /** @description Discovery Candidates refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryRefreshResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listAdminAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent administration audit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
}
