/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}/workbench": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncidentWorkbench"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminState"];
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/admin/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeams"];
        put?: never;
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/api/v1/admin/team-memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeamMemberships"];
        put?: never;
        post: operations["createTeamMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/team-memberships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTeamMembership"];
        trace?: never;
    };
    "/api/v1/admin/role-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoleBindings"];
        put?: never;
        post: operations["createRoleBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/role-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateRoleBinding"];
        trace?: never;
    };
    "/api/v1/admin/connector-enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConnectorAdminState"];
        put?: never;
        post: operations["createConnectorEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/connector-enrollments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateConnectorEnrollment"];
        trace?: never;
    };
    "/api/v1/admin/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRegisteredClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateRegisteredCluster"];
        trace?: never;
    };
    "/api/v1/admin/resource-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getResourceCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCatalogServices"];
        put?: never;
        post: operations["createCatalogService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/resource-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listResourceBindings"];
        put?: never;
        post: operations["confirmResourceBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/resource-bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["correctResourceBinding"];
        trace?: never;
    };
    "/api/v1/connectors/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordConnectorHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connectors/discovery-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshDiscoveryCandidates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
            /** @constant */
            session_mode: "cookie";
        };
        LoginResponse: {
            service?: string;
            /** @constant */
            status: "ok";
            request_id: string;
            expires_at: number;
            actor: components["schemas"]["Actor"];
        };
        LegacyActor: {
            actor_id: string;
            username: string;
            display_name: string;
            roles: string[];
            permissions: string[];
        };
        Actor: {
            id: string;
            username: string;
            display_name: string;
            roles: ("platform_administrator" | "sre")[];
            capabilities: string[];
            is_platform_administrator: boolean;
        };
        Incident: {
            id: string;
            title: string;
            /** @enum {unknown} */
            severity: "critical" | "high" | "medium" | "low";
            /** @enum {unknown} */
            status: "active" | "resolved";
            /** @enum {unknown} */
            lifecycle_state: "firing" | "stabilizing" | "resolved" | "reopened";
            /** @enum {unknown} */
            binding_status: "bound" | "unbound";
            cluster_id: string;
            cluster_name: string;
            /** @enum {unknown} */
            environment: "prod" | "staging" | "dev" | "test";
            namespace: string;
            alertname: string;
            workload_name: string | null;
            service_name: string | null;
            team_name: string | null;
            signal_count: number;
            evidence_revision: number;
            resolved_at: number | null;
            reopened_at: number | null;
            created_at: number;
            updated_at: number;
        };
        AlertSignal: {
            fingerprint: string;
            alertname: string;
            /** @enum {unknown} */
            status: "firing" | "recovered";
            /** @enum {unknown} */
            severity: "critical" | "high" | "medium" | "low";
            summary: string;
            workload_kind: string | null;
            workload_name: string | null;
            started_at: string | null;
            created_at: number;
            updated_at: number;
        };
        InvestigationSummary: {
            id: string;
            sequence: number;
            /** @enum {unknown} */
            status: "queued" | "running" | "paused" | "human_led" | "completed" | "failed" | "terminated";
            created_at: number;
            updated_at: number;
        };
        IncidentResourceContext: {
            cluster_id: string;
            cluster_name: string;
            /** @enum {unknown} */
            environment: "prod" | "staging" | "dev" | "test";
            /** @enum {unknown} */
            runtime_status: "online" | "offline" | "degraded";
            namespace: string;
            workload_kind: string | null;
            workload_name: string | null;
            deployment_target_id: string | null;
            service_id: string | null;
            service_name: string | null;
            resource_binding_id: string | null;
            binding_revision: number | null;
        };
        IncidentResponsibility: {
            /** @enum {unknown} */
            status: "assigned" | "unassigned";
            team_id: string | null;
            team_name: string | null;
        };
        RecoveryObservation: {
            id: string;
            evidence_revision: number;
            /** @enum {unknown} */
            status: "stabilizing" | "cancelled" | "resolved";
            observed_at: number;
            stabilizes_at: number;
            cancelled_at: number | null;
            resolved_at: number | null;
        };
        ActorResponse: {
            request_id: string;
            actor: components["schemas"]["Actor"];
        };
        IncidentListResponse: {
            request_id: string;
            incidents: components["schemas"]["Incident"][];
        };
        WorkbenchResponse: {
            request_id: string;
            incident: components["schemas"]["Incident"];
            resource_context: components["schemas"]["IncidentResourceContext"];
            alert_signals: components["schemas"]["AlertSignal"][];
            investigation: components["schemas"]["InvestigationSummary"] | null;
            evidence_steps: unknown[];
            judgment: null;
            recommended_actions: unknown[];
            recovery_observation: components["schemas"]["RecoveryObservation"] | null;
            responsibility: components["schemas"]["IncidentResponsibility"];
            actor_capabilities: string[];
            snapshot_revision: string;
            event_cursor: number;
        };
        AdminUser: {
            id: string;
            username: string;
            display_name: string;
            email?: string | null;
            active: boolean;
            updated_at: number;
        };
        UserCreateRequest: {
            username: string;
            display_name: string;
            email?: string | null;
            password: string;
            reason: string;
        };
        UserUpdateRequest: {
            display_name?: string;
            email?: string | null;
            password?: string;
            active?: boolean;
            reason: string;
        };
        TeamCreateRequest: {
            name: string;
            description?: string;
            reason: string;
        };
        TeamUpdateRequest: {
            name?: string;
            description?: string;
            active?: boolean;
            reason: string;
        };
        TeamMembershipCreateRequest: {
            user_id: string;
            team_id: string;
            reason: string;
        };
        TeamMembershipUpdateRequest: {
            active: boolean;
            reason: string;
        };
        RoleBindingCreateRequest: components["schemas"]["PlatformAdminBindingCreateRequest"] | components["schemas"]["SreBindingCreateRequest"];
        PlatformAdminBindingCreateRequest: {
            user_id: string;
            /** @constant */
            role: "platform_administrator";
            /** @constant */
            scope_type: "platform";
            scope_id?: null;
            reason: string;
        };
        SreBindingCreateRequest: {
            user_id: string;
            /** @constant */
            role: "sre";
            /** @constant */
            scope_type: "team";
            scope_id: string;
            reason: string;
        };
        RoleBindingUpdateRequest: {
            active: boolean;
            reason: string;
        };
        AdminTeam: {
            id: string;
            name: string;
            description: string;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        AdminTeamMembership: {
            id: string;
            user_id: string;
            team_id: string;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        AdminRoleBinding: {
            id: string;
            user_id: string;
            /** @enum {unknown} */
            role: "platform_administrator" | "sre";
            /** @enum {unknown} */
            scope_type: "platform" | "team";
            scope_id?: string | null;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        ConnectorEnrollment: {
            id: string;
            connector_id: string;
            cluster_id: string;
            active: boolean;
            registered: boolean;
        };
        Cluster: {
            cluster_id: string;
            connector_id: string;
            display_name: string;
            /** @enum {unknown} */
            environment: "prod" | "staging" | "dev" | "test";
            governance_notes: string;
            mutation_enabled: boolean;
            /** @enum {unknown} */
            runtime_status: "online" | "offline" | "degraded";
            failure_summary: string;
            last_heartbeat: number;
        };
        ConnectorEnrollmentCreateRequest: {
            connector_id: string;
            cluster_id: string;
            reason: string;
        };
        ConnectorEnrollmentUpdateRequest: {
            active?: boolean;
            rotate_credential?: boolean;
            reason: string;
        };
        ClusterUpdateRequest: {
            display_name?: string;
            /** @enum {unknown} */
            environment?: "prod" | "staging" | "dev" | "test";
            governance_notes?: string;
            mutation_enabled?: boolean;
            reason: string;
        };
        ConnectorRegistrationRequest: {
            connector_id: string;
            cluster_id: string;
            namespace_scope?: string[];
            capabilities?: string[];
        };
        ConnectorHeartbeatRequest: {
            connector_id: string;
            cluster_id: string;
            /** @enum {unknown} */
            status: "online" | "degraded";
            failure_summary?: string;
        };
        DiscoveryObservation: {
            namespace: string;
            workload_kind: string;
            workload_name: string;
            service_name?: string | null;
            service_hint?: string | null;
            team_hint?: string | null;
        };
        DiscoveryRefreshRequest: {
            connector_id: string;
            cluster_id: string;
            candidates: components["schemas"]["DiscoveryObservation"][];
        };
        DiscoveryCandidate: {
            id: string;
            cluster_id: string;
            namespace: string;
            workload_kind: string;
            workload_name: string;
            service_name: string | null;
            service_hint: string | null;
            team_hint: string | null;
            first_seen_at: number;
            last_seen_at: number;
            deployment_target_id: string | null;
            resource_binding_id: string | null;
            /** @enum {unknown} */
            binding_status: "bound" | "unbound";
        };
        CatalogService: {
            id: string;
            team_id: string;
            name: string;
            description: string;
            active: boolean;
            created_at: number;
            updated_at: number;
        };
        DeploymentTarget: {
            id: string;
            candidate_id: string;
            cluster_id: string;
            namespace: string;
            workload_kind: string;
            workload_name: string;
            service_identity: string | null;
            created_at: number;
        };
        ResourceBinding: {
            id: string;
            deployment_target_id: string;
            service_id: string;
            team_id: string;
            revision: number;
            confirmed_by: string;
            confirmed_at: number;
            updated_at: number;
        };
        ServiceCreateRequest: {
            team_id: string;
            name: string;
            description?: string;
            reason: string;
        };
        ResourceBindingCreateRequest: {
            candidate_id: string;
            service_id: string;
            reason: string;
        };
        ResourceBindingUpdateRequest: {
            service_id: string;
            reason: string;
        };
        DiscoveryRefreshResponse: {
            request_id: string;
            discovery_candidates: components["schemas"]["DiscoveryCandidate"][];
        };
        ResourceCatalogStateResponse: {
            request_id: string;
            discovery_candidates: components["schemas"]["DiscoveryCandidate"][];
            services: components["schemas"]["CatalogService"][];
            deployment_targets: components["schemas"]["DeploymentTarget"][];
            resource_bindings: components["schemas"]["ResourceBinding"][];
        };
        ServiceResponse: {
            request_id: string;
            service: components["schemas"]["CatalogService"];
        };
        ResourceBindingResponse: {
            request_id: string;
            resource_binding: components["schemas"]["ResourceBinding"];
        };
        ConnectorAdminStateResponse: {
            request_id: string;
            connector_enrollments: components["schemas"]["ConnectorEnrollment"][];
            clusters: components["schemas"]["Cluster"][];
        };
        ConnectorEnrollmentCredentialResponse: {
            request_id: string;
            connector_enrollment: components["schemas"]["ConnectorEnrollment"];
            credential?: string;
        };
        ClusterResponse: {
            request_id: string;
            cluster: components["schemas"]["Cluster"];
        };
        ConnectorClusterResponse: {
            request_id: string;
            /** @enum {unknown} */
            status: "registered" | "accepted";
            cluster: components["schemas"]["Cluster"];
        };
        AdminStateResponse: {
            request_id: string;
            users: components["schemas"]["AdminUser"][];
            teams: components["schemas"]["AdminTeam"][];
            team_memberships: components["schemas"]["AdminTeamMembership"][];
            role_bindings: components["schemas"]["AdminRoleBinding"][];
        };
        AdminUserResponse: {
            request_id: string;
            user: components["schemas"]["AdminUser"];
        };
        AdminTeamResponse: {
            request_id: string;
            team: components["schemas"]["AdminTeam"];
        };
        AdminTeamMembershipResponse: {
            request_id: string;
            team_membership: components["schemas"]["AdminTeamMembership"];
        };
        AdminRoleBindingResponse: {
            request_id: string;
            role_binding: components["schemas"]["AdminRoleBinding"];
        };
        AdminAuditResponse: {
            request_id: string;
            audit: {
                [key: string]: unknown;
            }[];
        };
        CsrfResponse: {
            /** @constant */
            status: "ok";
            request_id: string;
            csrf_token: string;
        };
        OkResponse: {
            /** @constant */
            status: "ok";
            request_id: string;
        };
        ErrorResponse: {
            /** @constant */
            status: "failed";
            request_id: string;
            error: {
                code: string;
                message: string;
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Normalized error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: {
        UserCreate: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        UserUpdate: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        TeamCreate: {
            content: {
                "application/json": components["schemas"]["TeamCreateRequest"];
            };
        };
        TeamUpdate: {
            content: {
                "application/json": components["schemas"]["TeamUpdateRequest"];
            };
        };
        TeamMembershipCreate: {
            content: {
                "application/json": components["schemas"]["TeamMembershipCreateRequest"];
            };
        };
        TeamMembershipUpdate: {
            content: {
                "application/json": components["schemas"]["TeamMembershipUpdateRequest"];
            };
        };
        RoleBindingCreate: {
            content: {
                "application/json": components["schemas"]["RoleBindingCreateRequest"];
            };
        };
        RoleBindingUpdate: {
            content: {
                "application/json": components["schemas"]["RoleBindingUpdateRequest"];
            };
        };
        ConnectorEnrollmentCreate: {
            content: {
                "application/json": components["schemas"]["ConnectorEnrollmentCreateRequest"];
            };
        };
        ConnectorEnrollmentUpdate: {
            content: {
                "application/json": components["schemas"]["ConnectorEnrollmentUpdateRequest"];
            };
        };
        ClusterUpdate: {
            content: {
                "application/json": components["schemas"]["ClusterUpdateRequest"];
            };
        };
        ConnectorRegistration: {
            content: {
                "application/json": components["schemas"]["ConnectorRegistrationRequest"];
            };
        };
        ConnectorHeartbeat: {
            content: {
                "application/json": components["schemas"]["ConnectorHeartbeatRequest"];
            };
        };
        DiscoveryRefresh: {
            content: {
                "application/json": components["schemas"]["DiscoveryRefreshRequest"];
            };
        };
        ServiceCreate: {
            content: {
                "application/json": components["schemas"]["ServiceCreateRequest"];
            };
        };
        ResourceBindingCreate: {
            content: {
                "application/json": components["schemas"]["ResourceBindingCreateRequest"];
            };
        };
        ResourceBindingUpdate: {
            content: {
                "application/json": components["schemas"]["ResourceBindingUpdateRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Cookie session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    reauthenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Fresh authentication recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getActor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listIncidents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible incidents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getIncidentWorkbench: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incident-scoped Workbench snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbenchResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getAdminState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UserCreate"];
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UserUpdate"];
        responses: {
            /** @description User updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamCreate"];
        responses: {
            /** @description Team created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamUpdate"];
        responses: {
            /** @description Team updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listTeamMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createTeamMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamMembershipCreate"];
        responses: {
            /** @description Membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamMembershipResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateTeamMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TeamMembershipUpdate"];
        responses: {
            /** @description Membership updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTeamMembershipResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listRoleBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administration state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoleBindingCreate"];
        responses: {
            /** @description Role binding created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoleBindingResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RoleBindingUpdate"];
        responses: {
            /** @description Role binding updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRoleBindingResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    getConnectorAdminState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector Enrollment and registered Cluster state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorAdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createConnectorEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorEnrollmentCreate"];
        responses: {
            /** @description Enrollment created and credential returned once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorEnrollmentCredentialResponse"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    updateConnectorEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorEnrollmentUpdate"];
        responses: {
            /** @description Enrollment rotated or revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorEnrollmentCredentialResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listRegisteredClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered Clusters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorAdminStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    updateRegisteredCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ClusterUpdate"];
        responses: {
            /** @description Cluster governance fields updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterResponse"];
                };
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getResourceCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource Catalog state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCatalogStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    listCatalogServices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource Catalog state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCatalogStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    createCatalogService: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ServiceCreate"];
        responses: {
            /** @description Service created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listResourceBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource Catalog state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCatalogStateResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
    confirmResourceBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ResourceBindingCreate"];
        responses: {
            /** @description Resource Binding confirmed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceBindingResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    correctResourceBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ResourceBindingUpdate"];
        responses: {
            /** @description Resource Binding corrected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceBindingResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    registerConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorRegistration"];
        responses: {
            /** @description Existing authenticated registration refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorClusterResponse"];
                };
            };
            /** @description First authenticated registration created Cluster presence */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorClusterResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    recordConnectorHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ConnectorHeartbeat"];
        responses: {
            /** @description Heartbeat recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorClusterResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    refreshDiscoveryCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DiscoveryRefresh"];
        responses: {
            /** @description Discovery Candidates refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryRefreshResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listAdminAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent administration audit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditResponse"];
                };
            };
            403: components["responses"]["Error"];
        };
    };
}
